### ISSUE TITLE
Update to Ubuntu 20.04.1?

### ISSUE THREAD

**Issue by issmirnov** [fubarhouse/docker-ansible#2]
Hey,

Now that the LTS Ubuntu 20.04.1 image has stabilized, does it make sense to release a new build for https://hub.docker.com/r/fubarhouse/docker-ubuntu2004-ansible?

Note: I'm not sure if a simple rebuild would be enough, since the `ubuntu:20.04` tag should pull the latest version.

**Comment by fubarhouse** [comment]
On an initial look, it seems a rebuild would help.
I'll organise it for after work tonight for you :)

**Comment by fubarhouse** [comment]
New images are built and pushed.

```
docker run -it fubarhouse/docker-ansible:focal lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

**Comment by issmirnov** [comment]
Awesome, thank you!
